version: "3.2"
services:
  networks_lab:
    image: alpine
    container_name:  networks_lab
    command: echo "installed networks networks_lab"
    restart: always
    networks:
      lab_net:

networks:
  lab_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24