version: "2.0"
services:
  portainer:
    image: portainer/portainer:1.24.0
    restart: always 
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #      - portainer_data:/data
      - /opt/portainer:/data